### ISSUE TITLE
ActionSupport.getUrl() returns invalid URI and does not reflect actual environment

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#31]
I have the following environment-configuration in my site.xml

```
  <domains>
    <url environment="production" default="true">http://www.mysite.ch</url>
    <url environment="staging" default="true">http://www-dev.mysite.ch</url>
    <url environment="development">http://mysite:8080</url>
  </domains>
```

Even though the environment of my Weblounge installation is set to `development`, a call to `ActionSupport.getUrl()` returns `http:/www.mysite.ch/myaction/mountpoint`. So, not only the hostname is wrong, there's also a missing slash after `http:/`

The expected result is `http://mysite:8080/myaction/moountpoint`

**Comment by ghost** [comment]
Fixed. Up until now, <code>WebUrl#getUrl()</code> returned the fulll url including the hostname. This has changed to returning the path portion only. 

As a side effect of this fix (needed to implement the integration test), actions can now specify a set of supported HTTP verbs, in order to be able to handle requests other than GET.
